// File generated by flutterfire configure. Do not edit.
import 'dart:io';
import 'package:firebase_core/firebase_core.dart';

/// `FlutterFire Configure` template for `firebase_options.dart`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isWindows) {
      return windows;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRbos-m9BLMQFaK-nAafAi_BGPGIDvNg',
    appId: '1:1006454812188:android:3e5d7908b377359194f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    databaseURL: 'https://rewardly-new-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXT-6Teaw4_wyPuPz-j5nEYA8AcLP3jbo',
    appId: '1:1006454812188:ios:1c142a39730a328394f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    databaseURL: 'https://rewardly-new-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-new.firebasestorage.app',
    iosBundleId: 'com.supreet.rewardly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXT-6Teaw4_wyPuPz-j5nEYA8AcLP3jbo',
    appId: '1:1006454812188:ios:1c142a39730a328394f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    databaseURL: 'https://rewardly-new-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-new.firebasestorage.app',
    iosBundleId: 'com.supreet.rewardly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRbos-m9BLMQFaK-nAafAi_BGPGIDvNg',
    appId: '1:1006454812188:android:3e5d7908b377359194f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    databaseURL: 'https://rewardly-new-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-new.firebasestorage.app',
  );
}
